### ISSUE TITLE
Publishing Submission without doi_info returns HTTP500

### ISSUE THREAD

**Issue by genie9** [CSCfi/metadata-submitter#464] opened 2022-05-31 13:25 UTC
#### Describe the bug
When publishing Submission without doi_info HTTP500 is returned. 

#### To Reproduce
Steps to reproduce the behaviour:
1. Crete folder in metadata submitter API
2. Try to publish the folder
3. See error HTTP500 KeyError: 'doiInfo'

#### Expected behavior

Backend should return HTTPBadRequest on missing doi_info and message that it's missing.

**Comment by csc-felipe** [comment] 2022-06-03 07:45
Duplicate of #412

**Closed** 2022-07-25 07:35 UTC
Labels: bug
